### ISSUE TITLE
Tile Sets list does not handle overflow

### ISSUE THREAD

**Issue by Tugark** [t-rex-tileserver/t-rex-viewer#3]
Using databases with lots of tables, the Tile Sets List on the left side exceeds the window size, leaving the user to scroll down the page, rather than just the list:
![now](https://user-images.githubusercontent.com/16555423/36988675-bb49b302-209f-11e8-94c0-bfba2c03ff00.PNG)

This could be fixed by adding the following overflow to `.TileList` in `src/TileList.css`:
```css
.TileList {
  position: absolute;
  left: 0;
  width: 25%;
  top: 0;
  height: 100%;
  background: #21252b;
 overflow: auto;
}
```
That way, it adds scrollbars if needed:
![unbenannt](https://user-images.githubusercontent.com/16555423/36988941-84f532a8-20a0-11e8-8dbd-d84b339d5c58.PNG)

Not really an important fix, but would turn it more readable and navigatable.

Best regards,

Lukas
